name: Compile paper

on:
  push:
    branches: [paper]
  pull_request:
  workflow_dispatch:

concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  compile:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2
      - uses: julia-actions/setup-julia@19bd4db8c427e07d56602f1c432e1a26a55d6735 # v1.8.1
        with:
          version: 1.8.1
          arch: x64
      - uses: julia-actions/cache@936559d9c8a8452e3426f2c76b596b5cdf10f442 # v1.1.3
      - uses: quarto-dev/quarto-actions/setup@d1d44ffb885dabd878c341ba7116a603843bb14c #v2.0.3
        with:
          version: 1.1.242
      - name: Install TeXLive
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -qq latexmk lmodern texlive-fonts-extra texlive-fonts-recommended texlive-latex-base texlive-latex-extra
        shell: bash
      - name: Compile paper
        run: |
          make all
          make clean
      - name: Create output directories
        run: |
          mkdir src
          cp -r -t src _extensions .JuliaFormatter.toml codes.lua CondaPkg.toml julia.bib Makefile Manifest.toml paper.qmd Project.toml README.md render.jl refs.bib setup.jl
          mkdir tex
          cp -r -t tex paper_files diagram.tex jss.bst jss.cls jsslogo.jpg julia.bib paper.tex refs.bib
        shell: bash
      - uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8 # v3.1.0
        with:
          name: paper
          path: |
            src/
            tex/
            LICENSE
            paper.pdf
