name: Docs

on:
  push:
    branches:
      - main
    tags:
      # When a new release is available
      - 'v*'
  pull_request:

concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  docs:
    permissions:
      contents: write
      statuses: write
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1'
      - uses: julia-actions/cache@v1
      - uses: julia-actions/julia-buildpkg@v1
      - run: |
          julia --project=docs -e '
            using Pkg
            Pkg.develop(PackageSpec(path=pwd()))
            Pkg.instantiate()'
      - run: julia --project=docs docs/make.jl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JULIA_DEBUG: Documenter # Print `@debug` statements
  multidocs:
    needs: docs
    permissions:
      contents: write
      statuses: write
    name: Multi-Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1'
      - uses: julia-actions/cache@v1
      - uses: julia-actions/julia-buildpkg@v1
      - run: |
          julia --project=docs -e '
            using Pkg
            Pkg.develop(PackageSpec(path=pwd()))
            Pkg.instantiate()'
      - run: julia --project=docs docs/make_aggregate.jl
        env:
          MULTIDOCS_ROOTPATH: ${{ github.event_name == 'pull_request' && format('/previews/PR{0}', github.event.number) || '/' }}
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: multidocs
          folder: docs/build
          target-folder: ${{ github.event_name == 'pull_request' && format('/previews/PR{0}', github.event.number) || '/' }}
