name: Docs

on:
  push:
    branches:
      - main
    tags:
      # When a new release is available
      - 'v*'
  pull_request:

concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  docs:
    permissions:
      contents: write
      statuses: write
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1'
      - uses: julia-actions/cache@v1
      - uses: julia-actions/julia-buildpkg@v1
      - run: |
          julia --project=docs -e '
            using Pkg
            Pkg.develop(PackageSpec(path=pwd()))
            Pkg.instantiate()'
      - run: julia --project=docs docs/make.jl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JULIA_DEBUG: Documenter # Print `@debug` statements
  multidocs:
    needs: docs
    permissions:
      contents: write
      statuses: write
    name: Multi-Documentation
    runs-on: ubuntu-latest
    env:
      MULTIDOCS_ROOTPATH: ${{ github.event_name == 'pull_request' && format('/previews/PR{0}', github.event.number) || '/' }}
    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1'
      - uses: julia-actions/cache@v1
      - uses: julia-actions/julia-buildpkg@v1
      - run: |
          julia --project=docs -e '
            using Pkg
            Pkg.develop(PackageSpec(path=pwd()))
            Pkg.instantiate()'
      - run: julia --project=docs docs/make_aggregate.jl
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: docs/build
          target-folder: ${{env.MULTIDOCS_ROOTPATH}}
      - uses: dobladov/github-status-action@v2
        if: success()
        with:
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: 'multidocumenter/deploy'
          description: 'MultiDocumenter build succeeded'
          target_url: 'https://devmotion.github.io/CalibrationAnalysis.jl${{env.MULTIDOCS_ROOTPATH}}'
          state: 'success'
          sha: ${{github.event.pull_request.head.sha || github.sha}}
      - uses: dobladov/github-status-action@v2
        if: failure()
        with:
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: 'multidocumenter/deploy'
          description: 'MultiDocumenter build failed'
          state: 'failure'
          sha: ${{github.event.pull_request.head.sha || github.sha}}
