name: format-check

on:
  push:
    branches: [paper]
  pull_request:
  workflow_dispatch:

concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2
      - uses: julia-actions/setup-julia@19bd4db8c427e07d56602f1c432e1a26a55d6735 # v1.8.1
        with:
          version: 1.7.3
          arch: x64
      - name: Install JuliaFormatter
        run: |
          using Pkg
          name = "JuliaFormatter"
          uuid = "98e50ef6-434e-11e9-1051-2b60c6c9e899"
          version = "1.0.9"
          Pkg.add(; name, uuid, version)
        shell: julia --color=yes {0}
      - name: Format Julia code
        run: |
          using JuliaFormatter
          format("."; verbose = true)
        shell: julia --color=yes {0}
      - name: Format check
        run: |
          out = Cmd(`git diff --name-only`) |> read |> String
          if out == ""
              exit(0)
          else
              @error "Some files have not been formatted !!!"
              write(stdout, out)
              exit(1)
          end
        shell: julia --color=yes {0}
